version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test:
            command: mvn clean verify -Dheadless=true 
            test_results_path: target/test-report.html 